mod 'boxen', '3.3.4.xdissent', :github_tarball => 'xdissent/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod "repository", "2.2.0", :github_tarball => "boxen/puppet-repository"